name: Terraform Deployment with Manual Approval

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  terraform-deploy-with-approval:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment:
      name: production
      # Define required reviewers for manual approval
      reviewers:
        - "Harish-0012"  # GitHub username of the approver
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v3

      - name: Configure GCP Credentials
        id: configure_gcp
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/554761590655/locations/global/workloadIdentityPools/new-pool/providers/github-oidc-provider'
          service_account: 'github-wif@no-migration.iam.gserviceaccount.com'

      - name: Set up Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Terraform Init
        id: terraform_init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -out=tfplan | tee terraform_plan.txt
      
      - name: Extract Terraform Changes
        id: extract_changes
        run: |
          grep -E '(\+|\-|\~)' terraform_plan.txt > terraform_changes.txt
          if [ -s "terraform_changes.txt" ]; then
            echo "Terraform changes:"
            cat terraform_changes.txt
          else
            echo "No Terraform changes detected"
          fi
        
      - name: Extract Commit Message
        id: extract_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Display Full Output
        run: |
          echo "-------------------------------------------------"
          echo "                   Workflow Summary               "
          echo "-------------------------------------------------"
          echo "Commit Message:"
          echo "${{ env.COMMIT_MESSAGE }}"
          echo "-------------------------------------------------"
          echo "Checkout Code Step"
          echo "Time: $(date +%Y-%m-%d-%H-%M-%S)"
          echo "-------------------------------------------------"
          echo "Configure GCP Credentials Step"
          echo "Time: $(date +%Y-%m-%d-%H-%M-%S)"
          echo "-------------------------------------------------"
          echo "Set up Terraform Step"
          echo "Time: $(date +%Y-%m-%d-%H-%M-%S)"
          echo "-------------------------------------------------"
          echo "Terraform Init Step"
          echo "Time: $(date +%Y-%m-%d-%H-%M-%S)"
          echo "-------------------------------------------------"
          echo "Terraform Plan Step"
          echo "Time: $(date +%Y-%m-%d-%H-%M-%S)"
          echo "-------------------------------------------------"
          echo "Terraform Plan Output:"
          cat terraform_plan.txt
          echo "-------------------------------------------------"
          echo "Extracted Terraform Changes Output:"
          cat terraform_changes.txt
          echo "-------------------------------------------------"

      # Manual approval step
      - name: Wait for Approval
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: wait-for-approval.yml  # Separate workflow or approval logic (if applicable)
          
      - name: Terraform Apply
        run: terraform apply tfplan
